### ISSUE TITLE
Is arbpp abandoned?

### ISSUE THREAD

**Issue by yurivict** [bluescarni/arbpp#5]
Are there any equivalents?

**Comment by bluescarni** [comment]
@yurivict as far as I know, there are no C++ interfaces for Arb.

arbpp was an early (failed) experiment to write a C++ interface based on operator overloading. This is difficult to do for Arb because its API always requires to pass in the working precision as an extra parameter, so that you have, e.g., an addition function that accepts in input 3 arguments (rather than 2).

**Comment by yurivict** [comment]
@bluescarni 
Thank you for this information.

**Comment by yurivict** [comment]
On the second thought, it should be possible to have working precision as template argument. For example, if one needs to work with fp numbers with up to 1024 mantissa bits one can just instantiate a template with such parameter and work with this type being free of the above problem.

**Comment by bluescarni** [comment]
yes, that would be an interesting option. It would mean however less flexibility for the selection of the precision at runtime, and it would also mean that, e.g., exposing such a type to Python would be quite clunky (you would need to pre-select a fixed set of precisions that you want to support).
